# Generated by Django 3.2.8 on 2021-11-14 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البدء'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/default.png', upload_to='profile/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف : '),
        ),
    ]
