# Generated by Django 3.2.8 on 2021-11-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211114_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialist',
            field=models.CharField(default=0, max_length=50, verbose_name='التخصص : '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile/default.png', upload_to='media/profile/', verbose_name='الصورة الشخصية'),
        ),
    ]
