# Generated by Django 3.2.8 on 2021-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211115_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='من أنا : '),
        ),
    ]
