# Generated by Django 3.2.8 on 2021-11-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_who_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
