# Generated by Django 3.2.8 on 2021-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211115_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=0, max_length=100, verbose_name='العنوان بالتفصيل '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.IntegerField(default='+20', verbose_name='رقم الهاتف '),
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مده الانتظار'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_houres',
            field=models.IntegerField(default=0, verbose_name='عدد ساعات العمل '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=60, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف  '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialist',
            field=models.CharField(max_length=80, verbose_name='التخصص : '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='من أنا (نبذه) '),
        ),
    ]
