# Generated by Django 3.2.8 on 2021-11-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211115_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='العنوان', max_length=100, verbose_name='العنوان بالتفصيل '),
        ),
    ]
