# Generated by Django 3.2.8 on 2021-11-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=150, verbose_name='العنوان بالتفصيل '),
        ),
    ]
