# Generated by Django 3.2.8 on 2021-11-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_phone',
            field=models.IntegerField(default=0, verbose_name='رقم الهاتف '),
        ),
    ]
