# Generated by Django 3.2.8 on 2021-11-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_number_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(default=0, max_length=60, verbose_name='دكتور :'),
            preserve_default=False,
        ),
    ]
