# Generated by Django 3.2.8 on 2021-11-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(max_length=100, verbose_name='العنوان بالتفصيل '),
        ),
    ]
