# Generated by Django 3.2.8 on 2021-11-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الفيسبوك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الفيسبوك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الفيسبوك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='yahoo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الفيسبوك'),
        ),
    ]
