# Generated by Django 3.2.8 on 2021-11-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211116_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='خدمات الدكتور: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='فيسبوك'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جوجل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تويتر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yahoo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ايميل'),
        ),
    ]
