# Generated by Django 3.2.8 on 2021-11-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(choices=[('سمنه', 'جراحه سمنة ومناظير'), ('اسنان', 'اسنان'), ('باطنه', 'باطنه'), ('امراض', 'امراض دم'), ('انف', 'انف واذن وحنجرة'), ('مخ', 'مخ واعصاب'), ('نساء', 'نساء وتوليد'), ('عظام', 'عظام'), ('اطفال', 'جراحة اطفال'), ('اوعيه', 'جراحة اوعية دموية'), ('قلب', 'قلب واوعية دموية'), ('اورام', 'جراحة اورام'), ('تخسيس', 'تخسيس وتغذية'), ('تجميل', 'جراحة تجميل'), ('اورام', 'اورام'), ('اطفال', 'اطفال حديثي الولادة'), ('نفسي', 'نفسي'), ('جلدية', 'جلدية')], max_length=60, verbose_name='دكتور :'),
        ),
    ]
